### ISSUE TITLE
bug with log rotation / aurora

### ISSUE THREAD

**Issue by ryanking** [honeycombio/rdslogs#16]
I am trying to set up a new aurora cluster (first time) with rdslogs.

I *think* that there is a problem where rdslogs fails to update when the slowquery log is rotated.

Here is why–

1. rdslogs stopped producing new events at exactly midnight UTC. logfile here https://gist.github.com/anonymous/1cdd223490481835be83f673d9ca40ef
2. it appears the slow query log was rotated at that time https://gist.github.com/90c2bd5c555eb8c327207ed745969c0f. Also the file size for the file that had been rotated appears to be the length of the 'marker' from the rdslogs output.

My guess is that aurora has some different log configs that plain mysql rds.

**Comment by maplebed** [comment]
I think you're on the right track.  We don't officially support Aurora yet, but I've filed a task to dig in to it a bit more. Can't say for sure when it will be addressed.  Thanks for the report!

**Comment by ryanking** [comment]
Even without official support, it almost works! :)

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
