### ISSUE TITLE
CSV parser doesn't work for mysql audit query logs

### ISSUE THREAD

**Issue by tredman** [honeycombio/rdslogs#21]
The MariaDb audit plugin uses a quoted CSV field to log the query when query auditing is configured. Unfortunately the standard go csv parser doesn't expect quoted fields that use single quotes:

```
20180327 19:15:02,myhost,myuser,10.0.0.0,43716513,145052182,QUERY,mydb,'SELECT * FROM foo WHERE foo_type=1 AND (bar_id=17 OR bar_id=0) AND (xyz=3543 OR xyz=0) ORDER BY abc, def',0
```

This type of log entry, due to its extra commas, will result in a `wrong number of fields in line` error. We'll probably need to scrap the current CSV parser and use something slightly more advanced.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
