### ISSUE TITLE
Confusing message if you don't specify your correct region

### ISSUE THREAD

**Issue by feorlen** [honeycombio/rdslogs#23]
A customer invoked `rdslogs` without a `--region` value and got the message 

`The list of instances we got back from RDS is empty. Check the region and authentication?`

They were unsure what to do after that, perhaps the message can mention `--region` specifically. (Providing a value worked for them after we investigated.)

Also, I looked into how region is handled and found inconsistent information: 

The README and `--help` output say the default value is `us-east-1`.

The only place the string "us-east-1" exists is in the `kubernetes/rdslogs.yml` configuration file. Should you still get this as default if you are not using k8s?

**Comment by tredman** [comment]
The default is set in the cli here: https://github.com/honeycombio/rdslogs/blob/master/cli/cli.go#L38

+1 mentioning the `--region` flag specifically in the output. I like output that steers users in the right direction as much as possible.

**Comment by feorlen** [comment]
Was Molly's recommendation! I came around to an obviously good idea somewhat later :)

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
