### ISSUE TITLE
Allow rdslogs to tail all the databases

### ISSUE THREAD

**Issue by willthames** [honeycombio/rdslogs#28]
Could rdslogs be changed to cope with more than one DB at a time, and infer DB type?

It already has DescribeDBInstances so it can definitely discover all the databases.

I appreciate that parallelising the log tailing and shipping might be more troublesome than just running multiple instances, and thus not worth the extra effort.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
