### ISSUE TITLE
handle log rotation

### ISSUE THREAD

**Issue by azhurbilo** [honeycombio/rdslogs#30]
in RDS postgresql logs rotated each hour

```
error/postgresql.log.2018-09-06-13 # lastest
error/postgresql.log.2018-09-06-12
error/postgresql.log.2018-09-06-11
```

I am running `docker run -ti -e AWS_ACCESS_KEY_ID=*** -e AWS_SECRET_ACCESS_KEY=*** honeycombio/rdslogs:1.107 --region us-west-2 --identifier DB_NAME -f error/postgresql.log.`

and it process only latest log file which has already exist "error/postgresql.log.2018-09-06-13" (don't handle rotation of new log file `error/postgresql.log.2018-09-06-14`)

Do I need restart `rdslogs` command each time to handle RDS log file rotation?

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
