### ISSUE TITLE
Authentication using AWS_WEB_IDENTITY_TOKEN_FILE  (AWS EKS IRSA) does not work

### ISSUE THREAD

**Issue by aleksmark** [honeycombio/rdslogs#48]
**Versions**
1.108

**Steps to reproduce**

1. Follow instructions to setup web idenitity token based authentication https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
2. Make sure there are no other credentials provided (~/.aws/config, ~/.aws/credentials, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables)
3. Run rdslogs in pod and see the output

**Additional context**

In my rdslogs pod, AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables are set, but the rdslogs is not able to create the sessions. 

The stdout log:

>Sending output to STDOUT
>2022/05/04 21:09:58 Unable to locate AWS credentials. You have a few options:
>- Create an IAM role for the host machine with the permissions to access RDS
>- Use an AWS shared config file (~/.aws/config)
>- Configure credentials on a development machine (via ~/.aws/credentials)
>- Or set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
 

The current aws-sdk-go version on the project supports web identity token auth (minimum version is 1.23.13)

According to this issue https://github.com/aws/aws-sdk-go/issues/3218, `session.NewSession()` should be used to create the session, instead of `session.New()`.

**Comment by MikeGoldsmith** [comment]
Thanks for raising the ticket @aleksmark - we'll take a look at get back to you.

**Comment by aleksmark** [comment]
Thank you for quick fix

**Comment by kentquirk** [comment]
There's still more work coming on this repository -- I'm working on the CI / build process and will be adding tagged releases within the next day. If you're building around this you might want to wait a day.

**Comment by kentquirk** [comment]
@aleksmark I'm still going to be doing a newly-tagged release of this project; however, it is also being sunset. Please see #51 for more.

**Comment by aleksmark** [comment]
@kentquirk Thank you for the notice.
