### ISSUE TITLE
This project is being sunset

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/rdslogs#51]
This project has outlived its useful lifespan, and will be archived in the future. The functionality provided is now better handled by the use of [agentless integrations](https://github.com/honeycombio/agentless-integrations-for-aws).

Please see our [OSS process document](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md#) for more.

If you are actively using this tool, please comment on this issue with your use case.

**Comment by aleksmark** [comment]
>If you are actively using this tool, please comment on this issue with your use case.

We are actively using the tool, streaming the log from Postgres RDS to our ELK stack

**Comment by MikeGoldsmith** [comment]
Hey @aleksmark - have you looked at our [AWS Agentless Integrations](https://github.com/honeycombio/agentless-integrations-for-aws/#mysql--postgresql-rds-integration-for-cloudwatch-logs)? This is the tool we're recommending over using rdslog and includes support for RDS Postgress. Is there anything blocking you from switching, or was the comment just to indicate you're a current user?

**Comment by aleksmark** [comment]
Hi @MikeGoldsmith I haven't looked at the AWS Agentless Integration yet. The integration works only with Honeycomb right?  We are using the rdslogs as standalone, to export the logs to our own ELK stack.

**Comment by MikeGoldsmith** [comment]
Yes, the AWS Agentless integrations are all aimed at sending telemetry day to Honeycomb. Same for rdslogs, just it's a little easier to redirect the output to another destination.

Thanks for providing feedback. With your use case above, we are still going to move forward with sunsetting this project with the AWS Agentless integrations as the recommended replacement. If you wish to continue to use the project, you're welcome to fork and maintain the project yourself for your needs.

**Comment by aleksmark** [comment]
Ok, thank you for clarification
